-- MySQL Script generated by MySQL Workbench
-- Sat Apr 25 09:51:49 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema SSAT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SSAT` DEFAULT CHARACTER SET utf8 ;
USE `SSAT` ;


-- -----------------------------------------------------
-- Table `SSAT`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSAT`.`Usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `nacionalidad` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `degree` VARCHAR(45) NULL DEFAULT NULL,
  `date` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SSAT`.`Calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSAT`.`Calificacion` (
  `idPuntoInteres` INT(11) NOT NULL,
  `idUsuario` INT(11) NOT NULL,
  `puntos` INT(11) NULL DEFAULT NULL,
  `fecha` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPuntoInteres`, `idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SSAT`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSAT`.`Categoria` (
  `idCategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SSAT`.`Discusion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSAT`.`Discusion` (
  `idDiscusion` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(90) NULL,
  `contenido` TEXT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `idUsuario` INT(11) NULL DEFAULT NULL,
  `categoria` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idDiscusion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SSAT`.`Nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSAT`.`Nacionalidad` (
  `idNacionalidad` INT(11) NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idNacionalidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 243
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SSAT`.`PuntoInteres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSAT`.`PuntoInteres` (
  `idPuntoInteres` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `paginaWeb` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(10) NULL DEFAULT NULL,
  `categoria` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idPuntoInteres`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SSAT`.`Respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSAT`.`Respuesta` (
  `idRespuesta` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(90) NULL DEFAULT NULL,
  `contenido` TEXT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `idDiscusion` INT(11) NULL DEFAULT NULL,
  `idUsuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idRespuesta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
